name: Build and Release

on:
  workflow_run:
    workflows: ["Test"]
    branches:
      - main
    types:
      - completed

jobs:
  version:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event_name == 'push'
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: 'main'
          ssh-key: ${{ secrets.SSH_KEY }}
      - name: Set version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Update version
        run: python scripts/update_version.py ${{ env.RELEASE_VERSION }}
      - name: Auto-commit changes
        uses: stefanzweifel/git-auto-commit-action@49620cd3ed21ee620a48530e81dba0d139c9cb80
        with:
          commit_message: Bump version to ${{ env.RELEASE_VERSION }}
          create_branch: true
          branch: release-${{ env.RELEASE_VERSION }}
      - name: Merge changes to main
        run: |
          git checkout "main"
          git merge "release-${{ env.RELEASE_VERSION }}" --no-edit
          git push


  dist:
    runs-on: ubuntu-latest
    needs: [version]
    name: Build package
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - run: python -m pip install -U setuptools
    - run: python -m pip install -e .[testing]
    - name: Build package
      run: tox -e build
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist

  dist_upload:
    runs-on: ubuntu-latest
    needs: [dist]
    name: Upload to PyPi
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_token }}
